# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Floyd <- function(cost, n) {
    .Call('SSL_Floyd', PACKAGE = 'SSL', cost, n)
}

MPLA <- function(r, s, t) {
    .Call('SSL_MPLA', PACKAGE = 'SSL', r, s, t)
}

